[tool.briefcase]
project_name = "P.I.E."
bundle = "com.usptu.td.apps.pieone"
version = "0.0.1"
url = "https://github.com/ustyuzhaninky/pieone"
license = "MIT license"
author = 'Konstantin Usiuzhanin'
author_email = "ustyuzhaninky@hotmail.com"

[tool.briefcase.app.pieone]
formal_name = "P.I.E. ONE"
description = "An example beeware[briefcase]+kivy GUI application demonstrating a simple Section 300 Imitator for students of Technological Department of Ufa State Petroleum Technological University."
icon = "src/pieone/resources/pieone"
sources = ['src/pieone']
requires = [
    'kivy>=2.1.0',
    'kivy[dev,full,sdl2]>=2.1.0',
    'docutils',
    'pygments',
    'pypiwin32',
    "kivy_deps.sdl2",
    "kivy_deps.angle"
]


[tool.briefcase.app.pieone.macOS]
requires = [
    'kivy[dev,full,sdl2]>=2.1.0',
    'docutils',
    'pygments',
    'pypiwin32',
    "kivy_deps.sdl2",
    "kivy_deps.angle"
]
run_post=[
    "source macos_pre_create.sh"
]

[tool.briefcase.app.pieone.linux]
requires = [
    'kivy[dev,full,sdl2]>=2.1.0',
    'docutils',
    'pygments',
    'pypiwin32',
    "kivy_deps.sdl2",
    "kivy_deps.angle"
]
run_post=[
    "source linux_post_build.sh"
]

[tool.briefcase.app.pieone.linux.appimage]
system_requires = [
    'gir1.2-webkit-3.0',
    'libcairo2-dev',
    'libgirepository1.0-dev',
    'libgtk-3-dev',
    'libpango1.0-dev',
    'librsvg2-dev',
    'libwebkitgtk-3.0-0',
]
linuxdeploy_plugins = [
    'DEPLOY_GTK_VERSION=3 gtk',
]

[tool.briefcase.app.pieone.linux.flatpak]
flatpak_runtime = 'org.gnome.Platform'
flatpak_runtime_version = '42'
flatpak_sdk = 'org.gnome.Sdk'

[tool.briefcase.app.pieone.windows]
requires = [
    'kivy[dev,full,sdl2]>=2.1.0',
    'docutils',
    'pygments',
    'pypiwin32',
    "kivy_deps.sdl2",
    "kivy_deps.angle"
]
run_post=[
    "win_post_create.ps1"
]

# Mobile deployments
[tool.briefcase.app.pieone.iOS]
requires = [
    'kivy[dev,full,sdl2]>=2.1.0',
    'docutils',
    'pygments',
    'pypiwin32',
    "kivy_deps.sdl2",
    "kivy_deps.angle"
]

[tool.briefcase.app.pieone.android]
requires = [
    'kivy[dev,full,sdl2]>=2.1.0',
    'docutils',
    'pygments',
    'pypiwin32',
    "kivy_deps.sdl2",
    "kivy_deps.angle"
]
