<TbrContent>:
    orientation: "vertical"
    MDLabel:
        text: ""
    MDIcon:
        icon: "robot-industrial"
        pos_hint: {"center_x": .5, "center_y": .5}
        font_size: 200
    MDLabel:
        text: "To roll out in next releases..."
        halign: 'center'
        adaptive_height: True
        font_style: "H2"
        padding_x: "24dp"
        theme_text_color: "Custom"
        text_color: app.theme_cls.text_color
    MDLabel:
        text: ""